apiVersion: apps/v1
kind: Deployment
metadata:
  name: benefits-service
  namespace: darwinx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: benefits-service
  template:
    metadata:
      labels:
        app: benefits-service
    spec:
      containers:
      - name: benefits-service
        image: darwinx/benefits-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: darwinx-secrets
              key: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: benefits-service
  namespace: darwinx
spec:
  selector:
    app: benefits-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
