apiVersion: v1
kind: Secret
metadata:
  name: darwinx-secrets
  namespace: darwinx
type: Opaque
stringData:
  mongo-uri: "mongodb://mongo:27017"
  jwt-secret: "change_this_to_a_secure_random_string"
  openai-api-key: "sk-..."
